/** 20 cream guest-website themes for different event types */

export type CreamThemeDef = {
  id: string
  name: string
  event: string
  /** Portal swatch */
  from: string
  to: string
  accent: string
  accentSoft: string
  bgTop: string
  bgMid: string
  bgBottom: string
  text: string
  muted: string
  titleFont: 'pacifico' | 'great-vibes' | 'cinzel' | 'playfair' | 'damion'
  thanksLabel: string
  thanksLine: string
  eyebrow: string
  layout: 'classic' | 'centered' | 'wide'
}

export const CREAM_THEMES: CreamThemeDef[] = [
  {
    id: 'cream-01-birthday',
    name: 'Cream 01 — Birthday',
    event: 'Birthday',
    from: '#c45c26',
    to: '#ffe8d6',
    accent: '#c45c26',
    accentSoft: 'rgba(196,92,38,0.18)',
    bgTop: '#fff8f2',
    bgMid: '#ffe8d6',
    bgBottom: '#fff5ee',
    text: '#3b2a22',
    muted: '#6b4a3a',
    titleFont: 'pacifico',
    thanksLabel: 'Thank you',
    thanksLine: 'With love — SV Live Events',
    eyebrow: 'Happy Birthday',
    layout: 'classic',
  },
  {
    id: 'cream-02-wedding',
    name: 'Cream 02 — Wedding',
    event: 'Marriage',
    from: '#9a3412',
    to: '#fef3c7',
    accent: '#9a3412',
    accentSoft: 'rgba(154,52,18,0.16)',
    bgTop: '#fffaf3',
    bgMid: '#fef3c7',
    bgBottom: '#fff7ed',
    text: '#3f2a1d',
    muted: '#7c5a45',
    titleFont: 'great-vibes',
    thanksLabel: 'With gratitude',
    thanksLine: 'Blessings — SV Live Events',
    eyebrow: 'Wedding Live',
    layout: 'classic',
  },
  {
    id: 'cream-03-engagement',
    name: 'Cream 03 — Engagement',
    event: 'Engagement',
    from: '#be185d',
    to: '#fce7f3',
    accent: '#be185d',
    accentSoft: 'rgba(190,24,93,0.14)',
    bgTop: '#fff7fb',
    bgMid: '#fce7f3',
    bgBottom: '#fff1f7',
    text: '#4a1d32',
    muted: '#8b4a66',
    titleFont: 'great-vibes',
    thanksLabel: 'Thank you',
    thanksLine: 'Celebrating love — SV Live Events',
    eyebrow: 'Engagement',
    layout: 'classic',
  },
  {
    id: 'cream-04-reception',
    name: 'Cream 04 — Reception',
    event: 'Reception',
    from: '#b45309',
    to: '#ffedd5',
    accent: '#b45309',
    accentSoft: 'rgba(180,83,9,0.16)',
    bgTop: '#fffbf5',
    bgMid: '#ffedd5',
    bgBottom: '#fff7ed',
    text: '#422006',
    muted: '#7c4a1e',
    titleFont: 'playfair',
    thanksLabel: 'Thank you for joining',
    thanksLine: 'Warm regards — SV Live Events',
    eyebrow: 'Reception',
    layout: 'wide',
  },
  {
    id: 'cream-05-sangeet',
    name: 'Cream 05 — Sangeet',
    event: 'Sangeet',
    from: '#a16207',
    to: '#fef9c3',
    accent: '#a16207',
    accentSoft: 'rgba(161,98,7,0.16)',
    bgTop: '#fffef5',
    bgMid: '#fef9c3',
    bgBottom: '#fefce8',
    text: '#422006',
    muted: '#78612a',
    titleFont: 'damion',
    thanksLabel: 'Dhanyavaad',
    thanksLine: 'Dance on — SV Live Events',
    eyebrow: 'Sangeet Night',
    layout: 'classic',
  },
  {
    id: 'cream-06-mehendi',
    name: 'Cream 06 — Mehendi',
    event: 'Mehendi',
    from: '#166534',
    to: '#dcfce7',
    accent: '#166534',
    accentSoft: 'rgba(22,101,52,0.14)',
    bgTop: '#f7fff9',
    bgMid: '#dcfce7',
    bgBottom: '#ecfdf5',
    text: '#14532d',
    muted: '#3f6b4e',
    titleFont: 'great-vibes',
    thanksLabel: 'Thank you',
    thanksLine: 'Henna & happiness — SV Live Events',
    eyebrow: 'Mehendi',
    layout: 'classic',
  },
  {
    id: 'cream-07-baby-shower',
    name: 'Cream 07 — Baby Shower',
    event: 'Baby Shower',
    from: '#0369a1',
    to: '#e0f2fe',
    accent: '#0369a1',
    accentSoft: 'rgba(3,105,161,0.14)',
    bgTop: '#f8fcff',
    bgMid: '#e0f2fe',
    bgBottom: '#f0f9ff',
    text: '#0c4a6e',
    muted: '#3d6f8c',
    titleFont: 'pacifico',
    thanksLabel: 'Thank you',
    thanksLine: 'Tiny blessings — SV Live Events',
    eyebrow: 'Baby Shower',
    layout: 'centered',
  },
  {
    id: 'cream-08-naming',
    name: 'Cream 08 — Naming Ceremony',
    event: 'Naming Ceremony',
    from: '#0f766e',
    to: '#ccfbf1',
    accent: '#0f766e',
    accentSoft: 'rgba(15,118,110,0.14)',
    bgTop: '#f6fffd',
    bgMid: '#ccfbf1',
    bgBottom: '#f0fdfa',
    text: '#134e4a',
    muted: '#3d6b66',
    titleFont: 'playfair',
    thanksLabel: 'Thank you',
    thanksLine: 'A new name, a new story — SV Live Events',
    eyebrow: 'Naming Ceremony',
    layout: 'classic',
  },
  {
    id: 'cream-09-housewarming',
    name: 'Cream 09 — Housewarming',
    event: 'Housewarming',
    from: '#b45309',
    to: '#ffedd5',
    accent: '#c2410c',
    accentSoft: 'rgba(194,65,12,0.15)',
    bgTop: '#fffaf5',
    bgMid: '#ffedd5',
    bgBottom: '#fff7ed',
    text: '#431407',
    muted: '#7c3a1e',
    titleFont: 'cinzel',
    thanksLabel: 'Welcome home',
    thanksLine: 'Griha Pravesh blessings — SV Live Events',
    eyebrow: 'Housewarming',
    layout: 'classic',
  },
  {
    id: 'cream-10-anniversary',
    name: 'Cream 10 — Anniversary',
    event: 'Anniversary',
    from: '#9f1239',
    to: '#ffe4e6',
    accent: '#9f1239',
    accentSoft: 'rgba(159,18,57,0.14)',
    bgTop: '#fff8f8',
    bgMid: '#ffe4e6',
    bgBottom: '#fff1f2',
    text: '#4c0519',
    muted: '#7f1d3a',
    titleFont: 'great-vibes',
    thanksLabel: 'Thank you',
    thanksLine: 'Years of love — SV Live Events',
    eyebrow: 'Anniversary',
    layout: 'classic',
  },
  {
    id: 'cream-11-corporate',
    name: 'Cream 11 — Corporate',
    event: 'Corporate',
    from: '#44403c',
    to: '#f5f5f4',
    accent: '#57534e',
    accentSoft: 'rgba(87,83,78,0.14)',
    bgTop: '#fafaf9',
    bgMid: '#f5f5f4',
    bgBottom: '#fafaf9',
    text: '#1c1917',
    muted: '#57534e',
    titleFont: 'cinzel',
    thanksLabel: 'Thank you',
    thanksLine: 'Presented by SV Live Events',
    eyebrow: 'Live Event',
    layout: 'wide',
  },
  {
    id: 'cream-12-concert',
    name: 'Cream 12 — Concert',
    event: 'Concert',
    from: '#7c2d12',
    to: '#fed7aa',
    accent: '#9a3412',
    accentSoft: 'rgba(154,52,18,0.16)',
    bgTop: '#fff7ed',
    bgMid: '#ffedd5',
    bgBottom: '#fffbeb',
    text: '#431407',
    muted: '#7c2d12',
    titleFont: 'playfair',
    thanksLabel: 'Encore',
    thanksLine: 'Live sound by SV Live Events',
    eyebrow: 'Live Concert',
    layout: 'centered',
  },
  {
    id: 'cream-13-kids-birthday',
    name: 'Cream 13 — Kids Birthday',
    event: 'Birthday',
    from: '#ea580c',
    to: '#ffedd5',
    accent: '#ea580c',
    accentSoft: 'rgba(234,88,12,0.16)',
    bgTop: '#fffaf5',
    bgMid: '#ffedd5',
    bgBottom: '#fff7ed',
    text: '#7c2d12',
    muted: '#9a3412',
    titleFont: 'pacifico',
    thanksLabel: 'Thank you!',
    thanksLine: 'Party time — SV Live Events',
    eyebrow: 'Birthday Party',
    layout: 'centered',
  },
  {
    id: 'cream-14-elegant-birthday',
    name: 'Cream 14 — Elegant Birthday',
    event: 'Birthday',
    from: '#854d0e',
    to: '#fef9c3',
    accent: '#854d0e',
    accentSoft: 'rgba(133,77,14,0.15)',
    bgTop: '#fffef7',
    bgMid: '#fefce8',
    bgBottom: '#fef9c3',
    text: '#422006',
    muted: '#713f12',
    titleFont: 'playfair',
    thanksLabel: 'Thank you',
    thanksLine: 'Celebrating beautifully — SV Live Events',
    eyebrow: 'Birthday Celebration',
    layout: 'classic',
  },
  {
    id: 'cream-15-thread',
    name: 'Cream 15 — Thread Ceremony',
    event: 'Thread Ceremony',
    from: '#b45309',
    to: '#fde68a',
    accent: '#b45309',
    accentSoft: 'rgba(180,83,9,0.16)',
    bgTop: '#fffbeb',
    bgMid: '#fef3c7',
    bgBottom: '#fff7ed',
    text: '#451a03',
    muted: '#78350f',
    titleFont: 'cinzel',
    thanksLabel: 'Namaskaram',
    thanksLine: 'Sacred moments — SV Live Events',
    eyebrow: 'Upanayanam',
    layout: 'classic',
  },
  {
    id: 'cream-16-half-saree',
    name: 'Cream 16 — Half Saree',
    event: 'Half Saree',
    from: '#9d174d',
    to: '#fce7f3',
    accent: '#9d174d',
    accentSoft: 'rgba(157,23,77,0.14)',
    bgTop: '#fff7fb',
    bgMid: '#fce7f3',
    bgBottom: '#fdf2f8',
    text: '#500724',
    muted: '#9d174d',
    titleFont: 'great-vibes',
    thanksLabel: 'Thank you',
    thanksLine: 'A graceful milestone — SV Live Events',
    eyebrow: 'Half Saree Function',
    layout: 'classic',
  },
  {
    id: 'cream-17-pooja',
    name: 'Cream 17 — Pooja / Festival',
    event: 'Pooja',
    from: '#c2410c',
    to: '#ffedd5',
    accent: '#c2410c',
    accentSoft: 'rgba(194,65,12,0.15)',
    bgTop: '#fffaf5',
    bgMid: '#ffedd5',
    bgBottom: '#fff7ed',
    text: '#7c2d12',
    muted: '#9a3412',
    titleFont: 'cinzel',
    thanksLabel: 'Om Shanti',
    thanksLine: 'Divine blessings — SV Live Events',
    eyebrow: 'Pooja Live',
    layout: 'centered',
  },
  {
    id: 'cream-18-graduation',
    name: 'Cream 18 — Graduation',
    event: 'Graduation',
    from: '#1e3a8a',
    to: '#dbeafe',
    accent: '#1e40af',
    accentSoft: 'rgba(30,64,175,0.14)',
    bgTop: '#f8fafc',
    bgMid: '#dbeafe',
    bgBottom: '#eff6ff',
    text: '#1e3a8a',
    muted: '#3b5b9a',
    titleFont: 'playfair',
    thanksLabel: 'Congratulations',
    thanksLine: 'Proud moments — SV Live Events',
    eyebrow: 'Graduation Live',
    layout: 'wide',
  },
  {
    id: 'cream-19-garden',
    name: 'Cream 19 — Garden Venue',
    event: 'Garden',
    from: '#3f6212',
    to: '#ecfccb',
    accent: '#4d7c0f',
    accentSoft: 'rgba(77,124,15,0.14)',
    bgTop: '#f7fee7',
    bgMid: '#ecfccb',
    bgBottom: '#f7fee7',
    text: '#365314',
    muted: '#4d7c0f',
    titleFont: 'great-vibes',
    thanksLabel: 'Thank you',
    thanksLine: 'Under the open sky — SV Live Events',
    eyebrow: 'Garden Celebration',
    layout: 'classic',
  },
  {
    id: 'cream-20-simple',
    name: 'Cream 20 — Simple Classic',
    event: 'General',
    from: '#78716c',
    to: '#fafaf9',
    accent: '#a16207',
    accentSoft: 'rgba(161,98,7,0.14)',
    bgTop: '#fafaf9',
    bgMid: '#f5f5f4',
    bgBottom: '#fafaf9',
    text: '#292524',
    muted: '#57534e',
    titleFont: 'playfair',
    thanksLabel: 'Thank you',
    thanksLine: 'Streamed by SV Live Events',
    eyebrow: 'Live Stream',
    layout: 'wide',
  },
]

/** Legacy Theme 1 id → cream birthday */
export const LEGACY_THEME_MAP: Record<string, string> = {
  'theme-1': 'cream-01-birthday',
}

export function getCreamTheme(designId?: string | null): CreamThemeDef | null {
  if (!designId) return CREAM_THEMES[0]
  const mapped = LEGACY_THEME_MAP[designId] || designId
  return CREAM_THEMES.find((t) => t.id === mapped) ?? null
}

export function isCreamTheme(designId?: string | null): boolean {
  if (!designId) return true
  if (LEGACY_THEME_MAP[designId]) return true
  return CREAM_THEMES.some((t) => t.id === designId)
}
